import { useEffect, useState } from 'react'
import { useParams, useSearchParams, Link } from 'react-router-dom'
import { motion, AnimatePresence } from 'framer-motion'
import { ShieldCheck, ShieldAlert, ShieldX, Clock, Copy, Check, FileText, Building2, CalendarClock, UserRound, KeyRound, Info } from 'lucide-react'
import { getReportVerification, type ReportVerificationRecord } from '@/lib/reportVerification'
import { formatDateTime, timeAgo, cn } from '@/lib/utils'
import { Skeleton } from '@/components/ui'

type Status = 'loading' | 'current' | 'obsolete' | 'tampered' | 'not-found'

const CONFIG: Record<
  Exclude<Status, 'loading'>,
  { icon: typeof ShieldCheck; title: string; badge: string; tone: string; chip: string; body: string }
> = {
  current: {
    icon: ShieldCheck,
    title: 'Verified',
    badge: 'Current version',
    tone: 'text-clay-600',
    chip: 'bg-clay-600/15 text-clay-600',
    body: 'This document matches the latest Section Report on record. No newer version has been generated since this was printed.',
  },
  obsolete: {
    icon: Clock,
    title: 'Genuine, but outdated',
    badge: 'Superseded',
    tone: 'text-gold-600',
    chip: 'bg-gold-600/15 text-gold-600',
    body: 'This report was genuinely generated by the portal, but a newer Section Report has since replaced it. Ask an officer for the current version.',
  },
  tampered: {
    icon: ShieldAlert,
    title: 'Verification code mismatch',
    badge: 'Link altered',
    tone: 'text-red-600',
    chip: 'bg-red-600/15 text-red-600',
    body: "This report ID exists, but the verification code in the link doesn't match our record. The link may have been altered — don't treat this document as verified.",
  },
  'not-found': {
    icon: ShieldX,
    title: 'Not found',
    badge: 'No record',
    tone: 'text-red-600',
    chip: 'bg-red-600/15 text-red-600',
    body: 'No report matches this code. This document did not come from the Matipid Officer Portal, or the link is broken.',
  },
}

function DetailRow({ icon: Icon, label, value, mono }: { icon: React.ElementType; label: string; value: string; mono?: boolean }) {
  return (
    <div className="flex items-start gap-3 py-2.5">
      <div className="w-7 h-7 rounded-lg bg-surface-800 flex items-center justify-center shrink-0 mt-0.5">
        <Icon size={13} className="text-surface-400" />
      </div>
      <div className="min-w-0 flex-1">
        <p className="text-[10px] font-semibold uppercase tracking-wide text-surface-500">{label}</p>
        <p className={cn('text-sm text-surface-200 break-words', mono && 'font-mono')}>{value}</p>
      </div>
    </div>
  )
}

function CopyCode({ code }: { code: string }) {
  const [copied, setCopied] = useState(false)
  return (
    <button
      type="button"
      onClick={async () => {
        try {
          await navigator.clipboard.writeText(code)
          setCopied(true)
          setTimeout(() => setCopied(false), 1500)
        } catch {
          // Clipboard unavailable — the code is already visible to copy by hand.
        }
      }}
      className="inline-flex items-center gap-1.5 text-[11px] font-medium text-surface-500 hover:text-surface-200 transition-colors"
    >
      <AnimatePresence mode="wait" initial={false}>
        {copied ? (
          <motion.span key="check" initial={{ scale: 0.6, opacity: 0 }} animate={{ scale: 1, opacity: 1 }} exit={{ scale: 0.6, opacity: 0 }} className="inline-flex items-center gap-1.5 text-clay-600">
            <Check size={12} /> Copied
          </motion.span>
        ) : (
          <motion.span key="copy" initial={{ scale: 0.6, opacity: 0 }} animate={{ scale: 1, opacity: 1 }} exit={{ scale: 0.6, opacity: 0 }} className="inline-flex items-center gap-1.5">
            <Copy size={12} /> Copy code
          </motion.span>
        )}
      </AnimatePresence>
    </button>
  )
}

export function VerifyReport() {
  const { reportId } = useParams<{ reportId: string }>()
  const [searchParams] = useSearchParams()
  const code = searchParams.get('c') ?? ''
  const [status, setStatus] = useState<Status>('loading')
  const [record, setRecord] = useState<ReportVerificationRecord | null>(null)

  useEffect(() => {
    let cancelled = false
    async function run() {
      if (!reportId) {
        setStatus('not-found')
        return
      }
      const rec = await getReportVerification(reportId).catch(() => null)
      if (cancelled) return
      if (!rec) {
        setStatus('not-found')
        return
      }
      setRecord(rec)
      if (code && rec.shortCode !== code) {
        setStatus('tampered')
        return
      }
      setStatus(rec.status === 'current' ? 'current' : 'obsolete')
    }
    run()
    return () => {
      cancelled = true
    }
  }, [reportId, code])

  const c = status === 'loading' ? null : CONFIG[status]
  const Icon = c?.icon

  return (
    <div className="max-w-md mx-auto px-4 sm:px-6 py-14">
      <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.35 }} className="card text-center">
        {status === 'loading' || !c || !Icon ? (
          <div className="py-2">
            <Skeleton className="w-14 h-14 rounded-2xl mx-auto mb-4" />
            <Skeleton className="h-4 w-32 mx-auto mb-2" />
            <Skeleton className="h-3 w-56 mx-auto mb-1" />
            <Skeleton className="h-3 w-44 mx-auto" />
          </div>
        ) : (
          <>
            <motion.div
              initial={{ scale: 0.7, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              transition={{ type: 'spring', stiffness: 260, damping: 18 }}
              className={cn('mx-auto mb-4 w-14 h-14 rounded-2xl flex items-center justify-center', c.chip)}
            >
              <Icon size={26} />
            </motion.div>
            <span className={cn('inline-block text-[10px] font-bold uppercase tracking-wider px-2.5 py-1 rounded-full mb-2.5', c.chip)}>{c.badge}</span>
            <h1 className="text-lg font-bold text-surface-100 mb-2">{c.title}</h1>
            <p className="text-sm text-surface-400 leading-relaxed mb-5">{c.body}</p>

            {record && (
              <div className="text-left border-t border-surface-700 pt-1 divide-y divide-surface-800">
                <DetailRow icon={FileText} label="Report" value={record.reportTitle} />
                <DetailRow icon={Building2} label="Section" value={record.sectionName} />
                <DetailRow icon={CalendarClock} label="Period" value={record.periodLabel} />
                {record.preparedByEmail && <DetailRow icon={UserRound} label="Prepared by" value={record.preparedByEmail} />}
                <DetailRow icon={Clock} label="Generated" value={`${formatDateTime(record.generatedAt)} \u00b7 ${timeAgo(record.generatedAt)}`} />
                <div className="flex items-start gap-3 py-2.5">
                  <div className="w-7 h-7 rounded-lg bg-surface-800 flex items-center justify-center shrink-0 mt-0.5">
                    <KeyRound size={13} className="text-surface-400" />
                  </div>
                  <div className="min-w-0 flex-1 flex items-center justify-between gap-3">
                    <div>
                      <p className="text-[10px] font-semibold uppercase tracking-wide text-surface-500">Verification code</p>
                      <p className="text-sm text-surface-200 font-mono">{record.shortCode}</p>
                    </div>
                    <CopyCode code={record.shortCode} />
                  </div>
                </div>
              </div>
            )}

            <div className="mt-5 pt-4 border-t border-surface-700 flex items-start gap-2 text-left">
              <Info size={13} className="text-surface-600 shrink-0 mt-0.5" />
              <p className="text-[11px] text-surface-600 leading-relaxed">
                Every report the portal generates is sealed with a code derived from its content and a random ID, recorded the moment it's created.
                Generating a new report automatically marks the previous one outdated, so an old copy can never quietly pass as current.
              </p>
            </div>
          </>
        )}
      </motion.div>
      <p className="text-center text-xs text-surface-600 mt-4">
        <Link to="/" className="hover:text-surface-400">
          Matipid Officer Portal
        </Link>
      </p>
    </div>
  )
}
